apiVersion: v1
kind: ReplicationController
metadata:
  name: insider-controller
spec:
  replicas: 2
  # selector identifies the set of Pods that this
  # replication controller is responsible for managing
  selector:
    app: insider
  # podTemplate defines the 'cookie cutter' used for creating
  # new pods when necessary
  template:
    metadata:
      labels:
        # Important: these labels need to match the selector above
        # The api server enforces this constraint.
        app: insider
    spec:
      containers:
      - name:  hackafe-insider
        image: ironsteel/hackafe-insider:v1 
        ports:
        - containerPort: 8080
