apiVersion: v1
kind: Pod
metadata:
  name: mysql
  labels:
    app: mysql
spec:
  containers:
    - resources:
        limits:
          cpu: 1.0
      image: mysql
      name: mysql
      env:
        - name: MYSQL_ROOT_PASSWORD
          # Change this password!
          value: YOUR_PASSWORD_HERE
        - name: MYSQL_DATABASE
          value: yaos
      ports:
        - containerPort: 3306
          name: mysql
      volumeMounts:
          # This name must match the volumes.name below.
        - name: mysql-persistent-storage
          mountPath: /var/lib/mysql
  volumes:
    - name: mysql-persistent-storage
      persistentVolumeClaim:
        claimName: myclaim-db


