apiVersion: v1
kind: ReplicationController
metadata:
  name: yaos 
spec:
  replicas: 2
  # selector identifies the set of Pods that this
  # replication controller is responsible for managing
  selector:
    app: yaos
  # podTemplate defines the 'cookie cutter' used for creating
  # new pods when necessary
  template:
    metadata:
      labels:
        # Important: these labels need to match the selector above
        # The api server enforces this constraint.
        app: yaos
    spec:
      containers:
      - name:  yaos
        image: ironsteel/yaos
        env:
          - name: LANG
            # Change this password!
            value: en_US.UTF-8
        ports:
        - containerPort: 8000
